# Dockerfile
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy the entire project into the container
COPY . /app

# Upgrade pip and install required packages
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Expose the port (Flask default is 5000)
EXPOSE 5000

# Environment variable for the Flask app
ENV FLASK_APP=app/app.py

# Command to run the app via gunicorn
CMD ["gunicorn", "app.app:app", "--bind", "0.0.0.0:5000"]