FROM python:3.9-slim

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

EXPOSE 5000

ENV FLASK_APP=app/app.py

CMD ["gunicorn", "app.app:app", "--bind", "0.0.0.0:5000"]