name: CI Pipeline

# Trigger the workflow on push events to the "main" branch.
on:
  push:
    branches:
      - main

jobs:
  build:
    # Run the job on the latest Ubuntu runner
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your source code using the official checkout action.
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up a Node.js environment (change to your preferred language or tool).
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      # Step 3: Install dependencies and run tests.
      - name: Install and Test
        run: |
          npm install
          npm run build
          npm test
